application: ingredient-annotation-platform
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: template/assets
  
- url: /hand/.*
  script: hand_annotation.application

- url: /bulk/.*
  script: bulk_operation.application

- url: /.*
  script: hand_annotation.application

libraries:
- name: jinja2
  version: latest
